### ISSUE TITLE
Argument `--block-size` does not accept units (or hex numbers), contrary to its helptext description.

### ISSUE THREAD

**Issue by eth-p** [sharkdp/hexyl#111] opened 2020-10-27 01:07 UTC
The `hexyl --help` description for the `--block-size` argument goes as follows:

```
        --block-size <SIZE>     Sets the size of the `block` unit to SIZE.
                                Examples: --block-size=1024, --block-size=4kB
```

However, when I attempt to run `hexyl "$(which hexyl)" -n 1block --block-size=4kB`, hexyl prints the following error:

```
Error: failed to parse `--block-size` arg "4kb" as positive integer

Caused by:
    invalid digit found in string
```

This is caused by the `block_size` argument being parsed as a positive i64 number, rather than as a data unit:

https://github.com/sharkdp/hexyl/blob/cc5b308fc9c2ca57ba176cf69a237f13428bb8e3/src/bin/hexyl.rs#L133-L142

**Side note:** If this bug was fixed, how would hexyl handle `--block-size=1block`? Should it be multiplying it by the default value, or would it be more appropriate to treat as an error to avoid any confusion?

**Edit:** It also doesn't accept hexadecimal numbers.

---

Note: I'm doing a class assignment regarding creating tests (from scratch) for an open-source command line program, and I chose hexyl for it. You might have a couple more of these on the way, depending on what the assignment brings to light :)

**Comment by sharkdp** [comment] 2020-10-29 19:31
> **Side note:** If this bug was fixed, how would hexyl handle `--block-size=1block`? Should it be multiplying it by the default value, or would it be more appropriate to treat as an error to avoid any confusion?

Interesting. I think that should be treated as an error, yes.

**Comment by ErichDonGubler** [comment] 2020-10-30 03:06
Disclaimer: I'm interested in resolving this. Right now, I'm just going to triage things, but I hope to have solution after I finish researching and put in my vote for my elections as a US resident.

The issue is valid, and the suggested resolution sounds great to me.

**Comment by merkrafter** [comment] 2021-11-06 22:54
May I give this issue a try? Looks like there is no other activity anymore.

**Comment by sharkdp** [comment] 2021-11-07 05:36
Yes, of course. Thank you

**Closed** 2021-11-14 08:26 UTC
Labels: bug, good first issue
