### ISSUE TITLE
Interrupting hexyl with ^C leaves ugly remnant

### ISSUE THREAD

**Issue by vi** [sharkdp/hexyl#35] opened 2019-01-12 11:55 UTC
![screenshot](https://user-images.githubusercontent.com/173219/51072870-69006c00-1679-11e9-8e8d-d6655c2d14be.png)

It should probably handle SIGINT and terminate the output as if it was EOF (but maybe with some mark):

    │00001410│ 57 37 f9 ae 0b ae 6c 8a ┊ df 0e d8 20 15 f1 d7 f6 │W7××•×l×┊×•× •×××│
    │00001420│ a5 5e 99 b0 bd bf 22 a7 ┊ b2 e0 ab ^C             | ×^×××"×┊×××^C   |

**Comment by sharkdp** [comment] 2019-01-13 15:13
Thank you for reporting this. This should be easy to fix, yes.

**Comment by sharkdp** [comment] 2019-01-14 10:07
Fixed in [v0.4.0](https://github.com/sharkdp/hexyl/releases/tag/v0.4.0).

**Comment by vi** [comment] 2019-01-14 10:41
![screenshot](https://user-images.githubusercontent.com/173219/51108129-261dd000-1802-11e9-8629-29eab261688b.png)

**Comment by DannyCork** [comment] 2019-03-16 19:16
This is what ctrl-c looks like on Mac OS X


![Screenshot 2019-03-16 at 19 15 49](https://user-images.githubusercontent.com/3512672/54480415-074ab280-4820-11e9-8512-fd39075e1ee0.png)

**Comment by sharkdp** [comment] 2019-04-04 19:54
If somebody has an idea how to fix this, let me know.

**Comment by domenpk** [comment] 2019-06-07 14:54
Well, part of the problem is synchronous handling of ctrl+c. If you move process exit into the handler, the situation improves. I'm not sure what's actually safe to be called from a signal handler in Rust though (normally described in: man 7 signal-safety).

It's still a bit of a problem, I assume because of stdout buffering. May need some uglier tricks to work around (setbuf?).

**Comment by secworks** [comment] 2020-02-07 07:25
A possibly related issue is that on MacOS, when running hexyl without any input the application can't be terminated. Like this:

<img width="349" alt="Screenshot 2020-02-07 at 08 24 53" src="https://user-images.githubusercontent.com/1833061/74009408-660ea280-4983-11ea-93ba-074505b9d3ba.png">

**Comment by sharkdp** [comment] 2020-02-10 19:08
@secworks That looks like a different bug to me (thank you for reporting it). It would be great if you could create a new ticket.

**Comment by sharkdp** [comment] 2020-03-09 20:06
With the changes in #84, this is now open again. In my terminal and on `zsh`, this is not an issue. But apparently it causes problems in some terminal/shell combinations.

**Comment by sandorex** [comment] 2020-06-12 11:54
@sharkdp Have you tried using alternative buffer when opening the application ?
The `smcup` / `rmcup` capability of the terminal ?

**Comment by bjorn3** [comment] 2020-06-12 16:31
Using an alternative buffer would mean that you have to handle scrolling yourself and you can't see the output anymore after you exit `hexyl`.

**Comment by sharkdp** [comment] 2020-06-17 16:06
I'm not sure what that means?

**Comment by sandorex** [comment] 2020-06-17 18:47
echo is when you press a key it displays on the terminal, but i think it is already disabled otherwise any key would be visible on a press

**Comment by bjorn3** [comment] 2020-06-17 19:28
Echo is enabled. I can still type stuff while I run `cat /dev/zero | pv -q -L 16 | hexyl` (read zeros at a rate of 16 bytes per second)

**Comment by sandorex** [comment] 2020-06-18 13:50
@bjorn3 You are right

I've been able to test it with little bash (does not work on zsh)
```bash
orig=$(stty -g)
stty -echo
hexyl /dev/urandom
stty $orig
```
And it doesnt show the `^C` anymore

**Comment by sharkdp** [comment] 2022-12-05 20:43
I'm closing this due to inactivity. And because I can not reproduce this on my machine. Please feel free to comment in case it should be re-opened.

**Closed by sharkdp** 2022-12-05 20:43 UTC
Labels: enhancement, help wanted
