### ISSUE TITLE
Feature Request: Specify length for displaying output 

### ISSUE THREAD

**Issue by figgis** [sharkdp/hexyl#157] opened 2022-05-06 09:21 UTC
I have some small binary masks, size 20x12 that I can display in my terminal using e.g hexdump:

```bash
❯ hexdump -v -e '20/1 " %02X" "\n"' mask_20x12.y
 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
 FF FF FF FF FF FF FF FF FF 00 00 00 FF FF FF FF FF FF FF FF
 FF FF FF FF FF FF FF FF FF 00 00 00 FF FF FF FF FF FF FF FF
 FF FF FF FF FF FF FF FF FF 00 00 00 FF FF FF FF FF FF FF FF
 FF FF FF FF FF FF FF FF 00 00 00 00 FF FF FF FF FF FF FF FF
 FF FF FF FF FF FF FF FF 00 00 00 00 FF FF FF FF FF FF FF FF
 FF FF FF FF FF FF FF FF 00 00 00 00 00 00 FF FF FF FF FF FF
 FF FF FF FF FF FF FF FF 00 00 00 00 00 00 00 FF FF FF FF FF
 FF FF FF FF FF FF FF 00 00 00 00 00 00 00 00 FF FF FF FF FF
 FF FF FF FF FF FF FF 00 00 00 00 00 00 00 00 FF FF FF FF FF
```

It would be wonderful if hexyl had the same capability.

**Comment by sharkdp** [comment] 2022-05-21 19:40
I'm sorry, but I'm not familiar with that `hexdump` option (-e/--format). Can you please tell us more?

**Comment by sharkdp** [comment] 2022-05-22 19:44
Is this a duplicate of #13?

**Comment by mhmdanas** [comment] 2022-06-04 14:34
> I'm sorry, but I'm not familiar with that hexdump option (-e/--format). Can you please tell us more?

This should help: https://www.man7.org/linux/man-pages/man1/hexdump.1.html#FORMATS

**Comment by sharkdp** [comment] 2022-12-05 21:24
I'm closing this due to inactivity. Please feel free to comment in case it should be re-opened.

**Closed by sharkdp** 2022-12-05 21:24 UTC

**Comment by figgis** [comment] 2022-12-05 21:40
inactivity - well, yes. Also just a feature request with a well specified output and an example how `hexdump` allows you to specify the width. Not much to comment on :)

**Comment by sharkdp** [comment] 2022-12-05 21:43
Well... I was asking above if this is a duplicate of #13 and never received an answer.

**Comment by figgis** [comment] 2022-12-05 21:46
My bad. Looks indeed like a duplicate of #13. 
I'm so sorry for waisting your time :)
Apologies!
